normie={
    'maincolor':'#c4394d',
    'fondo':'#f5abb8'
}
morado={
    'maincolor':'#7139c4',
    'fondo':'#bba0de'
}
azulado={
    'maincolor':'#0438b3',
    'fondo':'#9cb2e6'
}
verde={
    'maincolor':'#06cf3c',
    'fondo':'#affab4'
}
cyan={
    'maincolor':'#00ffff',
    'fondo':'#ccffff'
}
veceleste={
    'maincolor':'#13f28e',
    'fondo':'#b5f5d2'
}
anaranjado={
    'maincolor':'#f7bd1b',
    'fondo':'#ffdd80'
}
naranja={
    'maincolor':'#fa8314',
    'fondo':'#ffc085'
}
dorado={
    'maincolor':'#D4AF37',
    'fondo':'#fadf89'
}
dark={
    'maincolor':'#141414',
    'fondo':'#6b6b6b'
}